### PR TITLE
Gem2

### PR DESCRIPTION
**Pull request by jdbancal**
Corrected dimacs computations and updated the code to the new API of the gem library version 2.0.

### CODE REVIEW

**Comment by johanlofberg** [comment]
Can one of the admins verify this patch?

**Comment by jdbancal** [comment]
On a related note, @johanlofberg , I noticed that the refiner solver does not appear in the list of available yalmip solvers. For instance, in https://yalmip.github.io/allsolvers/ it is neither listed as an internal nor as an external solver. Should I add it in one of the lists?

**Comment by johanlofberg** [comment]
ok to test

**Comment by johanlofberg** [comment]
Sure feel free to add it

**Comment by jdbancal** [comment]
Ok, thanks!

**Pull request merged**
