### PR TITLE
Added registerjacobian to avoid recomputing jacobians

### PR DESCRIPTION
**Pull request by egidioln**
Hello again!

In the same line as https://github.com/yalmip/YALMIP/pull/1179, I added these `registerjacobian` functions that compute a jacobian for a constraint or expression and save it to avoid recomputing in the future. 

More specifically, when linearizing a constraint with many variables several times, the `jacobian` call becomes the bottleneck so computing it once and using it afterward saves a lot of time.

I am not sure if the `extra` struct would be the best place to save it, so feel free to give your opinion about it.

Also, attention to [@sdpvar/linearize.m#L30](https://github.com/egidioln/YALMIP/blob/30bcfe8da431aed55f749224014dc18752c10e8a/@sdpvar/linearize.m#L30) where I was wondering whether this should be an automatic feature (i.e., jacobians are registered whenever linearized is called for an `sdpvar`).

### CODE REVIEW

**Comment by johanlofberg** [comment]
I was going to say that you would have to be careful if it is changed after registered, but then I saw you did it on constraints only (which won't change) so I guess it should be safe.

I think the extra struct is the place to save this, but then one has to be careful about how it is used. If allowing the registration to act directly on an sdpvar, one would have to add code that resets when manipulating it, but that is for later

**Comment by johanlofberg** [comment]
Ah, saw your attention. The problem with that code is that you can do

```
x = sdpvar(1);
y = x^2;
assign(x,1);
z = jacobian(y);
y = x^2 + 1;
w = jacobian(y);
```

and then it will give the wrong result I think. Either the jacobian registration has to be cleared in all manipulations, or the registration should check if the object has changed since last registration. To do that, without saving an old version internally of "self", one could create some hash and save in registry.

**Comment by egidioln** [comment]
I actually did it thinking about constraints but https://github.com/yalmip/YALMIP/blob/30bcfe8da431aed55f749224014dc18752c10e8a/@sdpvar/registerjacobian.m could also be used for `sdpvar`'s directly, yielding this problem you mentioned when the variable is updated. 

Maybe only the `registerjacobian` function for constraints should be public for now, I guess.

**Comment by johanlofberg** [comment]
I don't think anyone will notice, but it is a robustification to be put on a todo-list.

**Comment by egidioln** [comment]
Nice, I removed the commented code and will try to make it more robust to be used for `sdpvar`'s too in the future.. Ideally, some operations (such as multiplication by scalars or by another expression that depends on the same variables) could even update the jacobian field automatically, instead of clearing it out.

**Pull request merged**
