### PR TITLE
Octave compatibility: replace findstr() with strfind() and strmatch() with strmatch_octavesafe()

### PR DESCRIPTION
**Pull request by teerav42**
Johan, let me know if it works this time.

### CODE REVIEW

**Comment by johanlofberg** [comment]
Great, all tests passed

**Comment by teerav42** [comment]
Awesome, glad to hear it. Just curious, when are you planning on a new release of YALMIP?

**Comment by teerav42** [comment]
Ha, sounds good! Looking forward to seeing it :)

**Comment by johanlofberg** [comment]
Tomorrows turned out to happen today

**Comment by teerav42** [comment]
Awesome. Thanks for the acknowledgment in the release notes! It was a pretty simple fix and I'm glad we got it done :)

**Comment by johanlofberg** [comment]
turns out it was still broken

`>> sdpsettings('solver','gurobi','gurobi.MIPGap',1e-1)
Error using strmatch_octavesafe
Too many input arguments.
Error in sdpsettings (line 308)
            k = strmatch_octavesafe(lowArg,names,'exact'); `

**Comment by teerav42** [comment]
Johan, I'm sorry I missed this last time around; I should have looked more carefully at each instance of `strmatch` that I replaced. I see that you pushed a fix---if anything else comes up related to this issue let me know and I will be willing to help if needed.

**Pull request merged**
