### PR TITLE
Trying to boost speed of subsref

### PR DESCRIPTION
**Pull request by jdbancal**
Another version of #699

### CODE REVIEW

**Comment by johanlofberg** [comment]
Can one of the admins verify this patch?

**Comment by johanlofberg** [comment]
ok to test

**Comment by jdbancal** [comment]
On my system, test `'test_sdpvar_replace/test1'` fails when running `runxunittests('xunit/core',1,'results')`, but it seems it also failed before this pull request

**Comment by johanlofberg** [comment]
Hmm, my magic response to the trigger code doesn't seemed to aev helped.

Regarding the test failure, check the code to see what fails and open an issue on that, with info about matlab version etc

**Comment by johanlofberg** [comment]
Giving up for the moment, merging to develop untested, we'll see...

**Comment by johanlofberg** [comment]
Passed

**Comment by jdbancal** [comment]
> Hmm, my magic response to the trigger code doesn't seemed to aev helped.
> 
> Regarding the test failure, check the code to see what fails and open an issue on that, with info about matlab version etc

I checked what was going on here and it appears that another library was overshadowing yalmip's `degree` function... So this was just a result of Matlab's limited support for packages and namespaces, the yalmip tests work fine!

**Comment by johanlofberg** [comment]
Aha, well that tells me I should make degree a method instead of a general function then.

**Pull request merged**
