### PR TITLE
Suppress Octave warnings from YALMIP-20210331 release version

### PR DESCRIPTION
**Pull request by robertgj**
This pull request is intended to suppress Octave warnings from the YALMIP-20210331 release version:
- suppress warnings about file name differing from function name
- use product of dimensions in extras/yalmip.m
- use "plus" not @plus in @sdpvar/mtimes.m
- check model return value in extras/primalize.m

Note that:
1. My fork has deleted the dev directory
2. I can't test these changes under MATLAB

### CODE REVIEW

**Comment by robertgj** [comment]
This pull request does not seem to have done what I expected. Attached is a patch file:
[YALMIP.patch.txt](https://github.com/yalmip/YALMIP/files/6357221/YALMIP.patch.txt)

**Comment by johanlofberg** [comment]
Hmm, I will have to be careful here not being fully confident in handling a pull request where stuff has been deleted

Removal of the annoying kitten is a clear reject.

Have to learn first how to cherry pick in pull-requests

Thanks for the effort

**Review by johanlofberg — COMMENTED** [review]
Why changing to string? Handles works in Octave 5.0 and 6.2 when I tried

**Comment by robertgj** [comment]
On Fri, 23 Apr 2021 07:47:48 -0700
Johan Löfberg ***@***.***> wrote:

> @johanlofberg commented on this pull request.
> 
> Why changing to string? Handles works in Octave 5.0 and 6.2 when I
> tried

I have been using Octave-6.1.0 for which @plus gives:

error: octave_base_value::function_value(): wrong type argument
'<unknown type>' error: called from
    mtimes at line 524 column 13

I will update to Octave-6.2.0.

Best wishes,

Robert Jenssen

**Comment by robertgj** [comment]
Hi,

Yes, Octave-6.2.0 fixes the problem with mtimes and bsxfun calling
@plus, perhaps due to this bug fix: https://savannah.gnu.org/bugs/?59661

bug #59661: classdef method call fails with
"octave_base_value::function_value(): wrong type argument '<unknown
type>'"

Best regards,

Robert Jenssen

**Comment by johanlofberg** [comment]
Good, because MATLAB does not support string format in bsxfun.

I'm using your changes as a basis for cleaning up code, I cannot pull it completely as there are stuff I want to do differently (such as removing the CVS headers completely instead of changing ö to o). Fixing those files was like a walk down memory lane...

**Comment by johanlofberg** [comment]
I took a lot of your QA fixes and manually updated develop (could not take full pull request as I wanted to do some things differently as previously discussed). Thanks again

**Pull request closed without merging**
