### PR TITLE
Update isVersionRecent.m

### LINKED ISSUE #1241: Bug in function isVersionRecent
The function `isVersionRecent` compares version numbers with different lengths and returns true if the version numbers are equal. But it breaks if the lenghts are equal and less than 3.

**Example**:

```matlab
>> isVersionRecent("2.0", "2.0")
```
returns the following error
```
Index exceeds the number of array elements. Index must not exceed 2.

Error in [isVersionRecent](matlab:matlab.internal.language.introspective.errorDocCallback('isVersionRecent', '/MATLAB Drive/isVersionRecent.m', 24)) ([line 24](matlab: opentoline('/MATLAB Drive/isVersionRecent.m',24,0)))
elseif version1Arr(3) >= version2Arr(3)

```

### PR DESCRIPTION
**Pull request by htadashi**
Fixes #1241

### CODE REVIEW

**Comment by johanlofberg** [comment]
Are you saying Chat-GPT isn't perfect?

**Comment by htadashi** [comment]
ChatGPT is very good, but it pales in comparison to your skills, @johanlofberg :)

**Comment by johanlofberg** [comment]
Out of curiosity, I added the prompt "it should work also when both arguments only have two numbers" and Chat-GPT adhered and added the lines

```
% Assume missing third component is zero
    if numel(version1Arr) < 3
        version1Arr(3) = 0;
    end
    if numel(version2Arr) < 3
        version2Arr(3) = 0;
    end
```

Almost exactly your addition, albeit slightly more compact as it skips the redundant use of the end-operator.

**Comment by htadashi** [comment]
Very interesting! I've read a [recent article](https://www.quantamagazine.org/the-unpredictable-abilities-emerging-from-large-ai-models-20230316) in Quanta Magazine about LLMs and it seems that a good prompt engineering can really leverage the power of these models.

**Pull request merged**
