### PR TITLE
put complex=0 in SeDuMi 1.3

### PR DESCRIPTION
**Pull request by araujoms**

### CODE REVIEW

**Comment by johanlofberg** [comment]
the complex tests in test_operator_geomean appears to fail on the test machine. do you see that locally?

**Comment by johanlofberg** [comment]
Caused by bug in latest sedumi patch (did not see it on my machine, then pulled sedumi and then failed)

```
K>> [x_s,y_s,info] = sedumi(-F_struc(:,2:end),-c,F_struc(:,1),K,pars);
Error: File: sedumi.m Line: 314 Column: 21
Invalid expression. When calling a function or indexing a
variable, use parentheses. Otherwise, check for mismatched
delimiters.
```

**Comment by araujoms** [comment]
If you look at line 314 of sedumi.m, there's an invalid character there that @siko1056 introduced in his latest commit.

**Comment by siko1056** [comment]
Sorry @araujoms and @johanlofberg, I ignored my own test suite before the release :bowing_man: 

Please proceed with SeDuMi 1.3.7 https://github.com/sqlp/sedumi/releases/tag/v1.3.7 .

**Pull request merged**
