### PR TITLE
Check if gem library is present before calling superiorto

### PR DESCRIPTION
**Pull request by jdbancal**
Sorry for the trouble, I did check whether matlab would complain about the absence of the gem library by removing the folder from matlab's path and using the 'clear' command, but it seems that a class which is part of matlab's path remains "known" even after removal from the path.

I added a small function which should fix the issue with very minimal overhead. Hope all will be good now, and thanks for your independent checks :+1:

### CODE REVIEW

**Comment by johanlofberg** [comment]
Won't that fail if user adds gem to path after having used yalmip in that session?

**Comment by jdbancal** [comment]
Indeed, if the user adds gem to the path after constructing an sdpvar, the class precedence will not be respected. A call to 'clear' would be needed in that case.

Would you have a better suggestion?

**Comment by johanlofberg** [comment]
try/catch is typically a quick and dirty trick

**Comment by jdbancal** [comment]
Ok, adopted the try/catch method

**Comment by johanlofberg** [comment]
Why not simply
```
try 
 superiorto('gem');
 superiorto('sgem');
catch
 % GEM not in path
end
```

**Comment by jdbancal** [comment]
Sure!

**Comment by jdbancal** [comment]
Actually, I put the check for sgem first to limit possible interaction with other libraries: I guess it's less likely that another user library would be called sgem than gem

**Pull request merged**
