### PR TITLE
Trying to boost speed of subsref

### PR DESCRIPTION
**Pull request by jdbancal**
For very large sparse matrices, transposition can be relatively costly timewise. For size `671898241x445241` for instance it can take a few seconds even when there are less than one nonzero element per line and column. Here is an attempt to avoid transposing `X.basis` when doing simple calls to subsrefs.

I did not have the opportunity to check this code extensively (there are three cases), so more tests should probably be run to make sure there it is ok. Also, the criterion to choose the appropriate subroutine might need some adjustement depending on the sparsity if `X.basis` (I only had very sparse matrices).

A similar improvement could also be applicable to `@ncvar/subsref.m`, but I am not very familiar with this part of the code.

### CODE REVIEW

**Comment by johanlofberg** [comment]
Can one of the admins verify this patch?

**Comment by johanlofberg** [comment]
Cool. I thought I had my local jenkins setup to automatically build pull-requests but that doesn't seem to start. I'll have a look before merging

ncvar is basically dead so don't waste any energy there

**Comment by johanlofberg** [comment]
BTW, I haven't cleaned up stuff yet or written anything about it, but you can test stuff using 

`runxunittests('xunit/core',1,'results')`

etc (test directories in dev/xunit)

When changing deep stuff like subsref, any bug would typically be caught there

**Comment by johanlofberg** [comment]
I'm gonna ask you a favor. I will close this pull-request, and ask you to make a new pull-request. Testing my test setup on pull-requests!

**Comment by jdbancal** [comment]
Sure!

**Pull request closed without merging**
